import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import Image from "next/image";
import styles from "../styles/Contact.module.css";
import { send } from 'emailjs-com';
import { useState } from "react";

import { toaster, ToasterContainer } from "baseui/toast";
import { Button } from "baseui/button";

const Contact = () => {
  const [name, setName] = useState('');
  const [number, setNumber] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');

  const SendEmail = async (e) => {
    e.preventDefault()

    console.log('send email')
    let templateParams = {
      from_name: name,
      to_name: '',
      email,
      number,
      subject: 'support request',
      message,
    }

    try {
      const email = await send(
        'gmail',
        'template_9dkmpw5',
        templateParams,
        'user_CQve8inPJM2qjaMb2Frzn'
      )
      console.log('email:', email)
    } catch (err) {
      console.log('err:', err)
    }

    toaster.positive("Message is send")
  }

  return (
    <ToasterContainer overrides={{
      Root: {
        style: ({ $theme }) => ({
          zIndex: '999999999999999'
        })
      }
    }}>


      <Head>
        <title>Sevi - Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <div className={styles.banner}>
        <img className={styles.bannerBg} src="/images/shape.svg" alt="" />
        <div className={styles.bannerTop}>
          <h1 className={styles.bannerHeader}>Contact Us</h1>
          <p className={styles.bannerDesp}>
            Thank you for your intrest in our services. Please try out the form
            below or e-email us.
          </p>
        </div>
        <div className={styles.bannerBottom}>
          <span className={styles.bannerImage}>
            <Image
              src="/images/contactImage.svg"
              alt=""
              width={825}
              height={550}
            />
          </span>
          <form className={styles.bannerForm}>
            <input
              type="text"
              placeholder="Your Name*"
              className={styles.bannerInput}
              onChange={(e) => setName(e.target.value)}
            />
            <input
              type="text"
              placeholder="Your Number*"
              className={styles.bannerInput}
              onChange={(e) => setNumber(e.target.value)}
            />
            <input
              type="text"
              placeholder="You Email*"
              className={styles.bannerInput}
              onChange={(e) => setEmail(e.target.value)}
            />
            <textarea
              rows="4"
              type="text"
              placeholder="Message"
              className={styles.bannerInput}
              onChange={(e) => setMessage(e.target.value)}
            />
            <Button onClick={SendEmail}>SEND MESSAGE</Button>
            {/* <button onClick={SendEmail}>SEND MESSAGE</button> */}
          </form>

        </div>
        <h1 className={styles.bannerServicesHeader}>Get In Touch</h1>
        <div className={styles.bannerServices}>
          <div className={styles.bannerService}>
            <div className={styles.serviceImage}>
              <Image src="/images/callIcon.svg" width={35} height={35} />
            </div>
            <span className={styles.serviceRight}>
              Support +254 743 623 754
              <br />
              Office +254 20 298 8000
            </span>
          </div>
          <div className={styles.bannerService}>
            <div className={styles.serviceImage}>
              <Image src="/images/smsIcon.svg" width={35} height={35} />
            </div>
            <span className={styles.serviceRight}>
              support@sevi.io
              <br />
              partner@sevi.io
            </span>
          </div>
          <div className={styles.bannerService}>
            <div className={styles.serviceImage}>
              <Image src="/images/locationIcon.svg" width={35} height={35} />
            </div>
            <span className={styles.serviceRight}>
              Luthers Plaza      <br />
              1st Floor, Left wing   <br />
              Nyerere Road, Nairobi <br />
              PO Box: 41987-00100 GPO
            </span>
          </div>
        </div>
      </div>
      <Footer />
    </ToasterContainer>

  );
};

export default Contact;
