import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import Banner2 from "../components/Banner2";
import Features from "../components/Features";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sevi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Header />
      <Banner />
      <Banner2 />
      <Features />
      <Footer />
    </>
  );
}
