import Head from "next/head";
import Header from "../components/Header";
import Banner from "../components/Banner";
import Banner2 from "../components/Banner2";
import Features from "../components/Features";
import Footer from "../components/Footer";
import Video from "../components/video";

export default function Home() {
  return (
    <div style={{
      padding: 0,
      margin: 0,
      boxSizing: 'border-box',
      // fontFamily: '-apple-system, Rubik, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
      width: '100%'
    }}>
      <Head>
        <title>Sevi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/seviS.svg" />
        <link
          rel="preload"
          href="/fonts/RecoletaAlt/RecoletaAlt-Bold.ttf"
          as="font"
          crossOrigin=""
        />
        {/* <script dangerouslySetInnerHTML={{
          __html: `(function(d,t) {
        var BASE_URL="https://app.chatwoot.com";
        var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
        g.src=BASE_URL+"/packs/js/sdk.js";
        s.parentNode.insertBefore(g,s);
        g.onload=function(){
          window.chatwootSDK.run({
            websiteToken: 'GMuxr6usUmx4gsGyzaZoSQVG',
            baseUrl: BASE_URL
          })
        }
      })(document,"script");`}} /> */}
      </Head>
      <Header />
      <Banner />
      <Banner2 />
      <Video />
      <Features />
      <Footer />
    </div>
  );
}
